project_name = "rg-sbus-lab-vitor"
location = "East US"
sbus_namespace_name = "sbus-lab-vitor"
azurerm_network_interface_name = "networknic01"
azurerm_subnet_name = "subnet01"
azurerm_virtual_network_name = "network01"